replicaCount: 1

image:
  tag: dev-latest

ingress:
  hosts:
    - host: order-service-dev.workshop.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: ConnectionStrings__DefaultConnection
    value: "Host=order-db;Database=orderservice_dev;Username=orderservice;Password=changeme"
  - name: CUSTOMER_SERVICE_URL
    value: "http://customer-service.decomposition-dev.svc.cluster.local"
  - name: PRODUCT_SERVICE_URL
    value: "http://product-service.decomposition-dev.svc.cluster.local"
  - name: INVENTORY_SERVICE_URL
    value: "http://inventory-service.decomposition-dev.svc.cluster.local"

persistence:
  enabled: false
