replicaCount: 2

image:
  tag: staging-latest

ingress:
  hosts:
    - host: ordermanager-staging.workshop.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75

env:
  - name: API_GATEWAY_URL
    value: "http://api-gateway.decomposition-staging.svc.cluster.local"
